### PR TITLE
$$$0002 refactor Numbers and hardcoded variables

### PR DESCRIPTION
**Pull request by balazsveghjo**
$$$0002 refactor by bw0101
 - ok
 - merge it

### CODE REVIEW

**Review by balazsveghjo — COMMENTED** [review]
it's ok now

**Review by balazsveghjo — COMMENTED** [review]
viewed, ok now

**Review by bw0101 — APPROVED** [review]
ok

**Comment by balazsveghjo** [comment]
ok, checked, merge it

**Comment by balazsveghjo** [comment]
yes, merge it

**Pull request merged**
